### ISSUE TITLE
Using TwiML method in controllers

### ISSUE THREAD

**Issue by devinrader** [TwilioDevEd/ivr-recording-csharp#1]
If a controller derives from TwilioController, why not use the TwiML() methed to return a TwimlResponse type?

https://github.com/TwilioDevEd/ivr-recording-csharp/blob/master/IVRRecording.Web/Controllers/AgentController.cs#L50

https://github.com/TwilioDevEd/ivr-recording-csharp/blob/master/IVRRecording.Web/Controllers/AgentController.cs#L68

**Comment by acamino** [comment]
@devinrader you right, when using a `TwilioController` is more appropriate to use [`TwiML`](https://github.com/twilio/twilio-csharp/blob/bd3319d83eb7187cf6c372a3805213d2ec20add2/src/Twilio.Mvc/TwilioController.cs#L21) helper method, since it is a nice wrapper around `new TwiMLResult`.

Since this is a minor change I pushed it directly to master, would you mind having a look at a2e7531 please?

**Comment by acamino** [comment]
@devinrader are you agree with the changes made on a2e7531? If you are, please close this one.

**Comment by devinrader** [comment]
+1
