### ISSUE TITLE
Returning ActionResult instead of TwiMLResult

### ISSUE THREAD

**Issue by devinrader** [TwilioDevEd/ivr-recording-csharp#2]
Think its totally fine for controller action methods to have a return type of ActionResult instead of the derived TwiMlResult.

**Comment by acamino** [comment]
@devinrader I tend to agree with you and Liskov :grin:. Nonetheless I found more intuitive to have a return type `TwiMLResult` if the response contains a `TwilioResponse`, in any other case I guess it's ok to use an `ActionResult`.

I'm using an `ActionResult` as the return type is [here](https://github.com/TwilioDevEd/ivr-recording-csharp/blob/a2e7531a6afe5b8326e28d26fe2a77b51638ce2c/IVRRecording.Web/Controllers/AgentController.cs#L29) because this method can either return plain content or a `TwilioResponse`.

_At Twilio what is your preference, using `ActionResult` or `TwiMLResult`? If as a community you have some guidelines, that would be awesome._

Please, let me know what do you think?

**Comment by devinrader** [comment]
Feels like the ASP.NET community has coalesced around making the return type of action methods the abstract ActionResult regardless of the concrete derived type actually being returned.

**Comment by acamino** [comment]
@devinrader I'll do the requested change. I think this change is an improvement since we'll keep consistency with the examples provided at https://www.twilio.com/blog/2012/02/twilio-for-net-developers-part-5-twilio-client-mvc-and-webmatrix-helper-libraries.html

**Comment by acamino** [comment]
@devinrader would you mind having a look at #3 please?

If you agree, we can close this issue.
